"""Correct foreign key references

Revision ID: 8fe990c20d7d
Revises: 
Create Date: 2024-07-25 10:46:28.336001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fe990c20d7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fond_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fond_id'], ['referentielfonds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint('positions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('fond_id')
        batch_op.drop_column('poids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fond_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('positions_ibfk_1', 'referentielfonds', ['fond_id'], ['id'])
        batch_op.alter_column('instrument_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.drop_table('performances')
    # ### end Alembic commands ###
