"""Add poids column to positions table

Revision ID: a4df3c622230
Revises: 8fe990c20d7d
Create Date: 2024-07-25 11:02:49.578802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4df3c622230'
down_revision = '8fe990c20d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('poids')

    # ### end Alembic commands ###
